[package]
name = "actimel"
version = "0.1.0"
edition = "2021"

[dependencies]
sysinfo = "0.29"  # For system information
netstat2 = "0.9"  # For network statistics
chrono = "0.4"    # For timestamp handling
log = "0.4"       # For logging
env_logger = "0.10" # For logging configuration
